#!/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
import argparse
import hashlib
import json
import os
import re
import subprocess
import tempfile
import time
from urllib.parse import quote_plus
import urllib3
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import as_completed


class Gitlab:
    class Project:
        def __init__(self, gitlab, info, conanfile, depends):
            self._gitlab = gitlab
            self.info = info
            self.conanfile = conanfile
            self.depends = depends

        @property
        def name(self):
            return None

        def not_depends(self, projects):
            return next((False for depend in self.depends if next((True for base in projects if base.name == depend), False)), True)

        def update(self):
            comment = self._gitlab.update_versions(self, "\n{name}/{version}@")
            if len(comment) > 0:
                comment = 'Auto updating dependencies.' + comment
                self._gitlab.update(
                    self.info,
                    'conanfile.txt',
                    self.conanfile,
                    'version/' + hashlib.md5(self.conanfile.encode()).hexdigest(),
                    comment
                )

        def up(self):
            print('Update: %s' % self.info['name'])
            self.update()
            return self

    class Package(Project):
        def __init__(self, gitlab, info, conanfile, depends, name, version):
            super().__init__(gitlab, info, conanfile, depends)
            self._name = name
            self._version = version

        @property
        def name(self):
            return self._name

        def update(self):
            comment = self._gitlab.update_versions(self, '"{name}/{version}@')
            comment += self._gitlab.update_versions(self, "'{name}/{version}@")
            if len(comment) > 0:
                version = re.search(r'''^\s+version\s*=\s*['"]([^'"]*).*$''', self._conanfile, re.MULTILINE)
                if version and version.group(1) == self._version:
                    values = self._gitlab.max_version(self._name, self._version).split('.')
                    while len(values) < 3:
                        values.append('0')
                    values[-1] = str(int(values[-1]) + 1)
                    self._version = '.'.join(values)
                    self._conanfile = self._conanfile[0:version.start(1)] + self._version + self._conanfile[version.end(1):]
                    comment = 'Auto updating to version {version}'.format(version=self._version) + comment
                    if not self._gitlab.update(self.info, 'conanfile.py', self._conanfile, 'version/' + self._version, comment):
                        return
            self._gitlab.set_version(self._name, self._version)

    def __init__(self, url, token):
        self._url = url
        self._token = token
        self._pattern = re.compile('([^/]*)/([^@]*)@')
        self._versions = {}
        urllib3.disable_warnings()

    def update_versions(self, project: Project, pattern):
        comment = ''
        for name, value in project.depends.items():
            tmp = project.conanfile.replace(
                pattern.format(name=name, version=value),
                pattern.format(name=name, version=self._versions[name])
            )
            if tmp != project.conanfile:
                project.conanfile = tmp
                comment += '\nupdate {name} {old} => {new}'.format(name=name, old=value, new=self._versions[name])
        return comment

    def set_version(self, name, value):
        self._versions[name] = value

    def get_projects(self, group):
        http = urllib3.PoolManager()
        r = http.request(
            method='GET',
            url='https://{gitlab}/api/v4/groups/{id}/projects?per_page=100'.format(id=quote_plus(group), gitlab=self._url),
            headers={'Private-Token': self._token}
        )
        return json.loads(r.data.decode())

    def get_file(self, project, file):
        http = urllib3.PoolManager()
        r = http.request(
            method='GET',
            url='https://{gitlab}/api/v4/projects/{id}/repository/files/{file}/raw?ref=master'.
                format(id=project, gitlab=self._url, file=file),
            headers={'Private-Token': self._token},
        )
        if r.status != 200:
            return None
        return r.data.decode()

    @staticmethod
    def _version_less(first, second):
        if first == second:
            return False
        f = first.split('.')
        s = second.split('.')
        for i in range(min(len(f), len(s))):
            if f[i] == s[i]:
                continue
            if f[i].isdecimal() and s[i].isdecimal():
                return int(f[i]) < int(s[i])
            else:
                return f[i] < s[i]
        return len(f) < len(s)

    def max_version(self, name, version):
        if name in self._versions:
            if self._version_less(self._versions[name], version):
                return version
            return self._versions[name]
        return version

    def read_deps(self, stream):
        deps = {}
        for line in stream:
            data = line.decode().strip()
            res = self._pattern.search(data)
            if res:
                self.set_version(name=res.group(1), value=self.max_version(name=res.group(1), version=res.group(2)))
                deps[res.group(1)] = res.group(2)
        return deps

    def make_project(self, project, data):
        with tempfile.TemporaryDirectory() as folder:
            with open(os.path.join(folder, 'conanfile.txt'), 'w') as fd:
                fd.write(data)
            info = subprocess.Popen(['conan', 'info', '-n', 'None', folder],
                                    stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
            for line in info.stdout:
                version = line.decode().strip()
                if version == 'PROJECT':
                    return self.Project(self, project, data, self.read_deps(info.stdout))
            return None

    def make_package(self, project, data):
        with tempfile.TemporaryDirectory() as folder:
            with open(os.path.join(folder, 'conanfile.py'), 'w') as fd:
                fd.write(data)
            info = subprocess.Popen(['conan', 'info', '-n', 'None', folder],
                                    stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
            for line in info.stdout:
                version = line.decode().strip()
                if version.endswith('@PROJECT'):
                    version = self._pattern.search(version)
                    return self.Package(self, project, data, self.read_deps(info.stdout), version.group(1), version.group(2))
            return None

    def get_conan_versions(self, project):
        print('Check project {name}'.format(name=project['name']))
        data = self.get_file(str(project['id']), 'conanfile.py')
        if data is not None:
            return self.make_package(project, data)
        data = self.get_file(str(project['id']), 'conanfile.txt')
        if data is not None:
            return self.make_project(project, data)
        return None

    def update(self, info, filename, content, branch, comment):
        print('UPDATE "{project}" with comment: {comment}'.format(project=info['name'], comment=comment))
        http = urllib3.PoolManager()

        r = http.request(
            method='PUT',
            url='https://{gitlab}/api/v4/projects/{id}/repository/files/{file_path}'.
                format(id=info['id'], file_path=quote_plus(filename), gitlab=self._url),
            headers={'Private-Token': self._token},
            fields={
                'branch': branch,
                'start_branch': 'master',
                'content': content,
                'commit_message': comment
            }
        )
        if r.status != 200:
            print('Error: %s' % r.data)
            return False

        r = http.request(
            method='POST',
            url='https://{gitlab}/api/v4/projects/{id}/merge_requests'.format(id=info['id'], gitlab=self._url),
            headers={'Private-Token': self._token},
            fields={
                'source_branch': branch,
                'target_branch': 'master',
                'title': comment,
                'remove_source_branch': 'true'
            }
        )
        if r.status != 201:
            print('Error: %s' % r.data)
            return False

        result = json.loads(r.data.decode())
        if not self.wait_pipeline(http, info['id'], result['sha']):
            return False

        r = http.request(
            method='PUT',
            url='https://{gitlab}/api/v4/projects/{id}/merge_requests/{merge_iid}/merge'.
                format(id=info['id'], merge_iid=result["iid"], gitlab=self._url),
            headers={'Private-Token': self._token}
        )
        if r.status != 200:
            print('Error: %s' % r.data)
            return False

        result = json.loads(r.data.decode())
        return self.wait_pipeline(http, info['id'], result['merge_commit_sha'])

    def wait_pipeline(self, http, project, sha):
        for _ in range(10):
            r1 = http.request(
                method='GET',
                url='https://{gitlab}/api/v4/projects/{id}/pipelines'.format(id=project, gitlab=self._url),
                headers={'Private-Token': self._token}
            )
            if r1.status != 200:
                return False
            pipelines = json.loads(r1.data.decode())
            pipeline_id, status = next(
                ((pipeline['id'], pipeline['status']) for pipeline in pipelines if pipeline['sha'] == sha),
                (None, None))
            if pipeline_id is not None:
                break
            print('\twaiting pipeline for sha {sha}'.format(sha=sha))
            time.sleep(15)
        if pipeline_id is None:
            print('Error %s' % json.dumps(pipelines))
            return False

        while status == 'running' or status == 'pending' or status == 'created':
            r1 = http.request(
                method='GET',
                url='https://{gitlab}/api/v4/projects/{id}/pipelines/{pipeline_id}'.
                    format(id=project, pipeline_id=pipeline_id, gitlab=self._url),
                headers={'Private-Token': self._token}
            )
            if r1.status != 200:
                return False
            tmp = json.loads(r1.data.decode())
            status = tmp['status']
            print('\twaiting pipeline {pipeline} for sha {sha}'.format(sha=sha, pipeline=pipeline_id))
            time.sleep(15)
        print('\tpipeline {pipeline} status {status}'.format(status=status, pipeline=pipeline_id))
        return status == 'success'


parser = argparse.ArgumentParser(description='Conan package version updater')
parser.add_argument('--gitlab', help='GitLab URL', required=True)
parser.add_argument('--gitlab-token', help='GitLab private token', required=True)
parser.add_argument('groups', help='gitlab goup list to update. All conan packages in this group will be updated', nargs='+')
args = parser.parse_args()

gitlab = Gitlab(args.gitlab, args.gitlab_token)
for group in args.groups:
    gitlab_projects = gitlab.get_projects(group)
    with ThreadPoolExecutor(max_workers=4) as executor:
        pkgs = (executor.submit(Gitlab.get_conan_versions, gitlab, project) for project in gitlab_projects)
        projects = [future.result() for future in as_completed(pkgs) if future.result() is not None]
        while len(projects) > 0:
            print('=' * 30)
            to_update = [project for project in projects if project.not_depends(projects)]
            if len(to_update) == 0:
                exit('Loop detected')
            pkgs = (executor.submit(Gitlab.Project.up, project) for project in to_update)
            for future in as_completed(pkgs):
                project = future.result()
                projects.remove(project)
